apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccxl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccxl
  template:
    metadata:
      labels:
        app: ccxl
    spec:
      containers:
      - image: okteto.dev/ccxl:latest
        name: ccxl
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/ccxl/main/S-html.zip"
        - name: Vless_UUID
          value: "802f44b7-1d19-400c-ad2e-f4d300bf4b1d"
        - name: Vless_Path
          value: "/dghGjutKw"
        - name: Vmess_UUID
          value: "802f44b7-1d19-400c-ad2e-f4d300bf4b1d"
        - name: Vmess_Path
          value: "/XsqotmUzt"
        - name: Share_Path
          value: "/v2link"
