apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsxe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fsxe
  template:
    metadata:
      labels:
        app: fsxe
    spec:
      containers:
      - image: okteto.dev/fsxe:latest
        name: fsxe
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/fsxe/main/S-html.zip"
        - name: Vless_UUID
          value: "3c8c3c7c-d081-423a-951d-ffd0167d3022"
        - name: Vless_Path
          value: "/kwdA2cxb3gfh"
        - name: Vmess_UUID
          value: "3c8c3c7c-d081-423a-951d-ffd0167d3022"
        - name: Vmess_Path
          value: "/uotBo3mjzo9ts"
        - name: Share_Path
          value: "/v2link"
